# Generated by Django 3.2.13 on 2023-11-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='board',
            new_name='board1',
        ),
    ]
